/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package speakmuch.libreria;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        Alumno classUnderTest = new Alumno();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
